language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'create database chitter;' -U postgres
  - rake db:migrate

  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rspec
